package com.harnessagent.persistence;

import org.springframework.jdbc.core.JdbcTemplate;

public final class JdbcStoreTestSupport {

    private JdbcStoreTestSupport() {
    }

    public static void createKnowledgeTables(JdbcTemplate jdbc) {
        jdbc.execute("""
                create table ha_knowledge_sources (
                    id varchar(128) primary key,
                    tenant_id varchar(128) not null,
                    owner_id varchar(128) not null,
                    agent_id varchar(128) not null,
                    title varchar(512) not null,
                    version varchar(128) not null,
                    visibility varchar(32) not null,
                    allowed_departments_json clob not null,
                    allowed_roles_json clob not null,
                    allowed_users_json clob not null,
                    update_policy varchar(128) not null,
                    source_type varchar(32) not null,
                    source_uri varchar(1024) not null,
                    index_status varchar(32) not null,
                    indexed_at timestamp,
                    status varchar(32) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null
                )
                """);
        jdbc.execute("create index idx_ha_knowledge_sources_tenant_updated on ha_knowledge_sources(tenant_id, updated_at)");
        jdbc.execute("""
                create table ha_knowledge_chunks (
                    id varchar(160) primary key,
                    source_id varchar(128) not null,
                    tenant_id varchar(128) not null,
                    title varchar(512) not null,
                    version varchar(128) not null,
                    chunk_index int not null,
                    content clob not null,
                    tokens_json clob not null,
                    source_type varchar(32) not null,
                    source_uri varchar(1024) not null
                )
                """);
        jdbc.execute("create index idx_ha_knowledge_chunks_source on ha_knowledge_chunks(source_id, chunk_index)");
        jdbc.execute("create index idx_ha_knowledge_chunks_tenant on ha_knowledge_chunks(tenant_id)");
        jdbc.execute("""
                create table ha_personal_memories (
                    id varchar(128) primary key,
                    tenant_id varchar(128) not null,
                    owner_id varchar(128) not null,
                    agent_id varchar(128) not null,
                    session_id varchar(128) not null,
                    layer_name varchar(64) not null,
                    title varchar(512) not null,
                    content clob not null,
                    status varchar(64) not null,
                    source_id varchar(128) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null
                )
                """);
        jdbc.execute("create index idx_ha_personal_memories_owner_agent on ha_personal_memories(tenant_id, owner_id, agent_id, updated_at)");
        jdbc.execute("""
                create table ha_rag_metrics (
                    id bigint generated by default as identity primary key,
                    tenant_id varchar(128) not null,
                    user_id varchar(128) not null,
                    query_text clob not null,
                    hit boolean not null,
                    candidate_count int not null,
                    permitted_count int not null,
                    failure_reason varchar(512),
                    created_at timestamp not null
                )
                """);
        jdbc.execute("create index idx_ha_rag_metrics_tenant_created on ha_rag_metrics(tenant_id, created_at)");
        jdbc.execute("""
                create table ha_rag_feedback (
                    id bigint generated by default as identity primary key,
                    tenant_id varchar(128) not null,
                    user_id varchar(128) not null,
                    query_text clob not null,
                    helpful boolean not null,
                    comment_text clob,
                    created_at timestamp not null
                )
                """);
        jdbc.execute("create index idx_ha_rag_feedback_tenant_created on ha_rag_feedback(tenant_id, created_at)");
    }

    public static void createToolTables(JdbcTemplate jdbc) {
        jdbc.execute("""
                create table ha_tool_definitions (
                    id varchar(128) primary key,
                    tenant_id varchar(128) not null,
                    name varchar(256) not null,
                    description clob not null,
                    owner_system varchar(128) not null,
                    owner_id varchar(128) not null,
                    source_type varchar(32) not null,
                    source_ref varchar(512) not null,
                    risk_level varchar(32) not null,
                    mutating boolean not null,
                    enabled boolean not null,
                    parameter_schema_json clob not null,
                    permission_policy_json clob not null,
                    audit_policy_json clob not null,
                    workload_type varchar(32) not null,
                    created_at timestamp not null,
                    updated_at timestamp not null
                )
                """);
        jdbc.execute("create index idx_ha_tool_definitions_tenant_name on ha_tool_definitions(tenant_id, name)");
        jdbc.execute("""
                create table ha_tool_audit_records (
                    id varchar(128) primary key,
                    occurred_at timestamp not null,
                    tenant_id varchar(128) not null,
                    user_id varchar(128) not null,
                    agent_id varchar(128) not null,
                    session_id varchar(128) not null,
                    tool_id varchar(128) not null,
                    tool_name varchar(256) not null,
                    source_type varchar(32) not null,
                    risk_level varchar(32) not null,
                    status varchar(64) not null,
                    sanitized_input_json clob not null,
                    sanitized_output_json clob not null,
                    duration_millis bigint not null,
                    approval_id varchar(128) not null,
                    reviewer_id varchar(128) not null,
                    idempotency_key varchar(256) not null,
                    failure_reason clob not null
                )
                """);
        jdbc.execute("create index idx_ha_tool_audit_tenant_time on ha_tool_audit_records(tenant_id, occurred_at)");
        jdbc.execute("""
                create table ha_tool_idempotency_records (
                    idempotency_key varchar(512) primary key,
                    parameter_fingerprint clob not null,
                    result_json clob not null,
                    created_at timestamp not null
                )
                """);
    }

    public static void createTelemetryTables(JdbcTemplate jdbc) {
        jdbc.execute("""
                create table ha_telemetry_events (
                    id varchar(128) primary key,
                    occurred_at timestamp not null,
                    type varchar(64) not null,
                    tenant_id varchar(128) not null,
                    user_id varchar(128) not null,
                    agent_id varchar(128) not null,
                    component varchar(256) not null,
                    duration_millis bigint not null,
                    attributes_json clob not null
                )
                """);
        jdbc.execute("create index idx_ha_telemetry_tenant_time on ha_telemetry_events(tenant_id, occurred_at)");
    }
}
