ALTER TABLE ha_session_messages COMMENT = 'Session message history scoped by tenant, user, agent, and session.';
ALTER TABLE ha_session_messages MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT 'Application generated message id.';
ALTER TABLE ha_session_messages MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_session_messages MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User isolation key.';
ALTER TABLE ha_session_messages MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_session_messages MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT 'Conversation session isolation key.';
ALTER TABLE ha_session_messages MODIFY COLUMN role VARCHAR(32) NOT NULL COMMENT 'Message role such as USER or ASSISTANT.';
ALTER TABLE ha_session_messages MODIFY COLUMN content TEXT NOT NULL COMMENT 'Message text persisted for replay and context.';
ALTER TABLE ha_session_messages MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Message creation timestamp.';

ALTER TABLE ha_security_audit COMMENT = 'Security and authorization audit events for governed operations.';
ALTER TABLE ha_security_audit MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT 'Application generated audit event id.';
ALTER TABLE ha_security_audit MODIFY COLUMN occurred_at TIMESTAMP(6) NOT NULL COMMENT 'Audit event timestamp.';
ALTER TABLE ha_security_audit MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_security_audit MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User associated with the audited action.';
ALTER TABLE ha_security_audit MODIFY COLUMN resource_type VARCHAR(64) NOT NULL COMMENT 'Governed resource category.';
ALTER TABLE ha_security_audit MODIFY COLUMN resource_id VARCHAR(256) NOT NULL COMMENT 'Governed resource identifier.';
ALTER TABLE ha_security_audit MODIFY COLUMN action VARCHAR(128) NOT NULL COMMENT 'Audited security action.';
ALTER TABLE ha_security_audit MODIFY COLUMN details_json TEXT NOT NULL COMMENT 'Structured audit details serialized as JSON text.';

ALTER TABLE ha_budget_counters COMMENT = 'Request and token budget counters by tenant, user, agent, and resource.';
ALTER TABLE ha_budget_counters MODIFY COLUMN counter_key VARCHAR(512) NOT NULL COMMENT 'Stable budget counter primary key.';
ALTER TABLE ha_budget_counters MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_budget_counters MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User isolation key.';
ALTER TABLE ha_budget_counters MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_budget_counters MODIFY COLUMN resource_id VARCHAR(256) NOT NULL COMMENT 'Budgeted provider or resource id.';
ALTER TABLE ha_budget_counters MODIFY COLUMN requests BIGINT NOT NULL COMMENT 'Consumed request count.';
ALTER TABLE ha_budget_counters MODIFY COLUMN tokens BIGINT NOT NULL COMMENT 'Consumed token estimate.';
ALTER TABLE ha_budget_counters MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT 'Last counter update timestamp.';

ALTER TABLE ha_agent_state COMMENT = 'Durable AgentScope state scoped to tenant, user, agent, session, and scope.';
ALTER TABLE ha_agent_state MODIFY COLUMN state_key VARCHAR(768) NOT NULL COMMENT 'Stable state primary key.';
ALTER TABLE ha_agent_state MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_agent_state MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User isolation key.';
ALTER TABLE ha_agent_state MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_agent_state MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT 'Session isolation key.';
ALTER TABLE ha_agent_state MODIFY COLUMN scope VARCHAR(256) NOT NULL COMMENT 'Agent state scope or memory segment.';
ALTER TABLE ha_agent_state MODIFY COLUMN state_value TEXT NOT NULL COMMENT 'Serialized state payload stored as text.';
ALTER TABLE ha_agent_state MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT 'Last state update timestamp.';

ALTER TABLE ha_snapshot_metadata COMMENT = 'Workspace snapshot metadata with tenant, agent, session, and task scope.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN id VARCHAR(64) NOT NULL COMMENT 'Application generated snapshot id.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT 'Session isolation key.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN task_id VARCHAR(256) NOT NULL COMMENT 'Task or run identifier associated with the snapshot.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Snapshot creation timestamp.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN backend_type VARCHAR(32) NOT NULL COMMENT 'Snapshot storage backend type.';
ALTER TABLE ha_snapshot_metadata MODIFY COLUMN location VARCHAR(1024) NOT NULL COMMENT 'Opaque snapshot storage location reference.';

ALTER TABLE ha_snapshot_content COMMENT = 'Snapshot artifact payload linked to snapshot metadata.';
ALTER TABLE ha_snapshot_content MODIFY COLUMN snapshot_id VARCHAR(64) NOT NULL COMMENT 'Snapshot metadata id and primary key.';
ALTER TABLE ha_snapshot_content MODIFY COLUMN content BLOB NOT NULL COMMENT 'Snapshot artifact payload.';

ALTER TABLE ha_knowledge_sources COMMENT = 'RAG knowledge source metadata and access policy.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN id VARCHAR(128) NOT NULL COMMENT 'Application generated knowledge source id.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN owner_id VARCHAR(128) NOT NULL COMMENT 'Knowledge source owner user id.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN title VARCHAR(512) NOT NULL COMMENT 'Knowledge source display title.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN version VARCHAR(128) NOT NULL COMMENT 'Knowledge source version label.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN visibility VARCHAR(32) NOT NULL COMMENT 'Knowledge visibility policy.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN allowed_departments_json TEXT NOT NULL COMMENT 'Allowed departments serialized as JSON text.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN allowed_roles_json TEXT NOT NULL COMMENT 'Allowed roles serialized as JSON text.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN allowed_users_json TEXT NOT NULL COMMENT 'Allowed users serialized as JSON text.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN update_policy VARCHAR(128) NOT NULL COMMENT 'Knowledge source update policy.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT 'Knowledge source lifecycle status.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Knowledge source creation timestamp.';
ALTER TABLE ha_knowledge_sources MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT 'Knowledge source update timestamp.';

ALTER TABLE ha_knowledge_chunks COMMENT = 'RAG searchable chunks derived from governed knowledge sources.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN id VARCHAR(160) NOT NULL COMMENT 'Stable knowledge chunk id.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN source_id VARCHAR(128) NOT NULL COMMENT 'Knowledge source id.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN title VARCHAR(512) NOT NULL COMMENT 'Knowledge source title copied for citation.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN version VARCHAR(128) NOT NULL COMMENT 'Knowledge source version copied for citation.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN chunk_index INT NOT NULL COMMENT 'Chunk order within the source.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN content TEXT NOT NULL COMMENT 'Chunk text used only after permission filtering.';
ALTER TABLE ha_knowledge_chunks MODIFY COLUMN tokens_json TEXT NOT NULL COMMENT 'Search tokens serialized as JSON text.';

ALTER TABLE ha_rag_metrics COMMENT = 'RAG retrieval metrics for hit rate, permission filtering, and no-answer analysis.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Database generated metric id.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User associated with retrieval.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN query_text TEXT NOT NULL COMMENT 'Original retrieval query stored for governed analytics.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN hit BOOLEAN NOT NULL COMMENT 'Whether retrieval produced accessible evidence.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN candidate_count INT NOT NULL COMMENT 'Candidate chunk count before permission filtering.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN permitted_count INT NOT NULL COMMENT 'Candidate chunk count after permission filtering.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN failure_reason VARCHAR(512) COMMENT 'No-answer or retrieval failure reason code.';
ALTER TABLE ha_rag_metrics MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Metric creation timestamp.';

ALTER TABLE ha_rag_feedback COMMENT = 'User feedback for RAG answers and no-answer outcomes.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Database generated feedback id.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User associated with feedback.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN query_text TEXT NOT NULL COMMENT 'Original retrieval query associated with feedback.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN helpful BOOLEAN NOT NULL COMMENT 'Whether the user marked the answer helpful.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN comment_text TEXT COMMENT 'Optional feedback comment text.';
ALTER TABLE ha_rag_feedback MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Feedback creation timestamp.';

ALTER TABLE ha_tool_definitions COMMENT = 'Governed tool registry with schema, permission, risk, and audit policy.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN id VARCHAR(128) NOT NULL COMMENT 'Application generated tool id.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN name VARCHAR(256) NOT NULL COMMENT 'Tool name exposed to orchestrators.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN description TEXT NOT NULL COMMENT 'Tool purpose description.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN owner_system VARCHAR(128) NOT NULL COMMENT 'Owning enterprise system.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN owner_id VARCHAR(128) NOT NULL COMMENT 'Tool owner user or service id.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN source_type VARCHAR(32) NOT NULL COMMENT 'Tool source type such as internal, MCP, or agent.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN source_ref VARCHAR(512) NOT NULL COMMENT 'Opaque tool source reference.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN risk_level VARCHAR(32) NOT NULL COMMENT 'Governance risk level.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN mutating BOOLEAN NOT NULL COMMENT 'Whether tool execution can mutate external state.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN enabled BOOLEAN NOT NULL COMMENT 'Whether the tool can be executed.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN parameter_schema_json TEXT NOT NULL COMMENT 'Parameter schema serialized as JSON text.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN permission_policy_json TEXT NOT NULL COMMENT 'Permission policy serialized as JSON text.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN audit_policy_json TEXT NOT NULL COMMENT 'Audit policy serialized as JSON text.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Tool registration timestamp.';
ALTER TABLE ha_tool_definitions MODIFY COLUMN updated_at TIMESTAMP(6) NOT NULL COMMENT 'Tool update timestamp.';

ALTER TABLE ha_tool_audit_records COMMENT = 'Tool execution audit records with sanitized input and output.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN id VARCHAR(128) NOT NULL COMMENT 'Application generated tool audit id.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN occurred_at TIMESTAMP(6) NOT NULL COMMENT 'Tool audit event timestamp.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User isolation key.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN session_id VARCHAR(128) NOT NULL COMMENT 'Session isolation key.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN tool_id VARCHAR(128) NOT NULL COMMENT 'Tool definition id.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN tool_name VARCHAR(256) NOT NULL COMMENT 'Tool name at execution time.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN source_type VARCHAR(32) NOT NULL COMMENT 'Tool source type at execution time.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN risk_level VARCHAR(32) NOT NULL COMMENT 'Tool risk level at execution time.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN status VARCHAR(64) NOT NULL COMMENT 'Tool execution status.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN sanitized_input_json TEXT NOT NULL COMMENT 'Sanitized tool input serialized as JSON text.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN sanitized_output_json TEXT NOT NULL COMMENT 'Sanitized tool output serialized as JSON text.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN duration_millis BIGINT NOT NULL COMMENT 'Tool execution duration in milliseconds.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN approval_id VARCHAR(128) NOT NULL COMMENT 'High-risk approval id when present.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN reviewer_id VARCHAR(128) NOT NULL COMMENT 'High-risk reviewer id when present.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN idempotency_key VARCHAR(256) NOT NULL COMMENT 'Tool idempotency key supplied by caller.';
ALTER TABLE ha_tool_audit_records MODIFY COLUMN failure_reason TEXT NOT NULL COMMENT 'Execution denial or failure reason.';

ALTER TABLE ha_tool_idempotency_records COMMENT = 'Stored tool results used to enforce idempotent mutating executions.';
ALTER TABLE ha_tool_idempotency_records MODIFY COLUMN idempotency_key VARCHAR(512) NOT NULL COMMENT 'Stable idempotency key for tenant, tool, and caller key.';
ALTER TABLE ha_tool_idempotency_records MODIFY COLUMN parameter_fingerprint TEXT NOT NULL COMMENT 'Canonical parameter fingerprint used for conflict detection.';
ALTER TABLE ha_tool_idempotency_records MODIFY COLUMN result_json TEXT NOT NULL COMMENT 'Stored tool execution result serialized as JSON text.';
ALTER TABLE ha_tool_idempotency_records MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL COMMENT 'Idempotency record creation timestamp.';

ALTER TABLE ha_telemetry_events COMMENT = 'Runtime telemetry events for API, RAG, tool, budget, and orchestration flows.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN id VARCHAR(128) NOT NULL COMMENT 'Application generated telemetry event id.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN occurred_at TIMESTAMP(6) NOT NULL COMMENT 'Telemetry event timestamp.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN type VARCHAR(64) NOT NULL COMMENT 'Telemetry event type.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN tenant_id VARCHAR(128) NOT NULL COMMENT 'Tenant isolation key.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN user_id VARCHAR(128) NOT NULL COMMENT 'User isolation key.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN agent_id VARCHAR(128) NOT NULL COMMENT 'Agent isolation key.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN component VARCHAR(256) NOT NULL COMMENT 'Component that emitted the event.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN duration_millis BIGINT NOT NULL COMMENT 'Observed duration in milliseconds.';
ALTER TABLE ha_telemetry_events MODIFY COLUMN attributes_json TEXT NOT NULL COMMENT 'Telemetry attributes serialized as JSON text.';
