COMMENT ON TABLE ha_owner_scope_migration_activity IS 'Owner-scope migration metadata for the personal Agent persistence transition.';
COMMENT ON COLUMN ha_owner_scope_migration_activity.id IS 'Stable migration metadata id.';
COMMENT ON COLUMN ha_owner_scope_migration_activity.migration_name IS 'Flyway migration name that created the owner-scope projection.';
COMMENT ON COLUMN ha_owner_scope_migration_activity.migrated_at IS 'Timestamp when the owner-scope projection migration ran.';
COMMENT ON COLUMN ha_owner_scope_migration_activity.notes IS 'Operational notes for backup, rollback, and compatibility review.';

COMMENT ON COLUMN ha_session_messages.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_session_messages.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_security_activity.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_security_activity.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_budget_counters.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_budget_counters.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_agent_state.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_agent_state.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_snapshot_metadata.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_snapshot_metadata.owner_id IS 'Best-effort owner id for historical snapshots; new writes store the personal owner.';
COMMENT ON COLUMN ha_knowledge_sources.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_knowledge_chunks.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_knowledge_chunks.owner_id IS 'Personal owner id copied from the source metadata.';
COMMENT ON COLUMN ha_knowledge_chunks.agent_id IS 'Agent id copied from the source metadata.';
COMMENT ON COLUMN ha_personal_memories.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_rag_metrics.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_rag_metrics.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_rag_feedback.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_rag_feedback.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_tool_definitions.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_tool_activity_records.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_tool_activity_records.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_tool_idempotency_records.owner_scope_id IS 'Owner scope id for personal tool idempotency records.';
COMMENT ON COLUMN ha_tool_idempotency_records.owner_id IS 'Personal owner id for personal tool idempotency records.';
COMMENT ON COLUMN ha_tool_idempotency_records.agent_id IS 'Agent id for personal tool idempotency records.';
COMMENT ON COLUMN ha_tool_idempotency_records.session_id IS 'Session id for personal tool idempotency records.';
COMMENT ON COLUMN ha_tool_idempotency_records.tool_id IS 'Tool id for personal tool idempotency records.';
COMMENT ON COLUMN ha_tool_pending_confirmations.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_tool_pending_confirmations.owner_id IS 'Personal owner id copied from the historical user column.';
COMMENT ON COLUMN ha_telemetry_events.owner_scope_id IS 'Owner scope id copied from the historical isolation column.';
COMMENT ON COLUMN ha_telemetry_events.owner_id IS 'Personal owner id copied from the historical user column.';
