COMMENT ON TABLE ha_session_messages IS 'Session message history scoped by tenant, user, agent, and session.';
COMMENT ON COLUMN ha_session_messages.id IS 'Application generated message id.';
COMMENT ON COLUMN ha_session_messages.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_session_messages.user_id IS 'User isolation key.';
COMMENT ON COLUMN ha_session_messages.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_session_messages.session_id IS 'Conversation session isolation key.';
COMMENT ON COLUMN ha_session_messages.role IS 'Message role such as USER or ASSISTANT.';
COMMENT ON COLUMN ha_session_messages.content IS 'Message text persisted for replay and context.';
COMMENT ON COLUMN ha_session_messages.created_at IS 'Message creation timestamp.';

COMMENT ON TABLE ha_security_audit IS 'Security and authorization audit events for governed operations.';
COMMENT ON COLUMN ha_security_audit.id IS 'Application generated audit event id.';
COMMENT ON COLUMN ha_security_audit.occurred_at IS 'Audit event timestamp.';
COMMENT ON COLUMN ha_security_audit.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_security_audit.user_id IS 'User associated with the audited action.';
COMMENT ON COLUMN ha_security_audit.resource_type IS 'Governed resource category.';
COMMENT ON COLUMN ha_security_audit.resource_id IS 'Governed resource identifier.';
COMMENT ON COLUMN ha_security_audit.action IS 'Audited security action.';
COMMENT ON COLUMN ha_security_audit.details_json IS 'Structured audit details serialized as JSON text.';

COMMENT ON TABLE ha_budget_counters IS 'Request and token budget counters by tenant, user, agent, and resource.';
COMMENT ON COLUMN ha_budget_counters.counter_key IS 'Stable budget counter primary key.';
COMMENT ON COLUMN ha_budget_counters.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_budget_counters.user_id IS 'User isolation key.';
COMMENT ON COLUMN ha_budget_counters.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_budget_counters.resource_id IS 'Budgeted provider or resource id.';
COMMENT ON COLUMN ha_budget_counters.requests IS 'Consumed request count.';
COMMENT ON COLUMN ha_budget_counters.tokens IS 'Consumed token estimate.';
COMMENT ON COLUMN ha_budget_counters.updated_at IS 'Last counter update timestamp.';

COMMENT ON TABLE ha_agent_state IS 'Durable AgentScope state scoped to tenant, user, agent, session, and scope.';
COMMENT ON COLUMN ha_agent_state.state_key IS 'Stable state primary key.';
COMMENT ON COLUMN ha_agent_state.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_agent_state.user_id IS 'User isolation key.';
COMMENT ON COLUMN ha_agent_state.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_agent_state.session_id IS 'Session isolation key.';
COMMENT ON COLUMN ha_agent_state.scope IS 'Agent state scope or memory segment.';
COMMENT ON COLUMN ha_agent_state.state_value IS 'Serialized state payload stored as text.';
COMMENT ON COLUMN ha_agent_state.updated_at IS 'Last state update timestamp.';

COMMENT ON TABLE ha_snapshot_metadata IS 'Workspace snapshot metadata with tenant, agent, session, and task scope.';
COMMENT ON COLUMN ha_snapshot_metadata.id IS 'Application generated snapshot id.';
COMMENT ON COLUMN ha_snapshot_metadata.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_snapshot_metadata.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_snapshot_metadata.session_id IS 'Session isolation key.';
COMMENT ON COLUMN ha_snapshot_metadata.task_id IS 'Task or run identifier associated with the snapshot.';
COMMENT ON COLUMN ha_snapshot_metadata.created_at IS 'Snapshot creation timestamp.';
COMMENT ON COLUMN ha_snapshot_metadata.backend_type IS 'Snapshot storage backend type.';
COMMENT ON COLUMN ha_snapshot_metadata.location IS 'Opaque snapshot storage location reference.';

COMMENT ON TABLE ha_snapshot_content IS 'Snapshot artifact payload linked to snapshot metadata.';
COMMENT ON COLUMN ha_snapshot_content.snapshot_id IS 'Snapshot metadata id and primary key.';
COMMENT ON COLUMN ha_snapshot_content.content IS 'Snapshot artifact payload.';

COMMENT ON TABLE ha_knowledge_sources IS 'RAG knowledge source metadata and access policy.';
COMMENT ON COLUMN ha_knowledge_sources.id IS 'Application generated knowledge source id.';
COMMENT ON COLUMN ha_knowledge_sources.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_knowledge_sources.owner_id IS 'Knowledge source owner user id.';
COMMENT ON COLUMN ha_knowledge_sources.title IS 'Knowledge source display title.';
COMMENT ON COLUMN ha_knowledge_sources.version IS 'Knowledge source version label.';
COMMENT ON COLUMN ha_knowledge_sources.visibility IS 'Knowledge visibility policy.';
COMMENT ON COLUMN ha_knowledge_sources.allowed_departments_json IS 'Allowed departments serialized as JSON text.';
COMMENT ON COLUMN ha_knowledge_sources.allowed_roles_json IS 'Allowed roles serialized as JSON text.';
COMMENT ON COLUMN ha_knowledge_sources.allowed_users_json IS 'Allowed users serialized as JSON text.';
COMMENT ON COLUMN ha_knowledge_sources.update_policy IS 'Knowledge source update policy.';
COMMENT ON COLUMN ha_knowledge_sources.status IS 'Knowledge source lifecycle status.';
COMMENT ON COLUMN ha_knowledge_sources.created_at IS 'Knowledge source creation timestamp.';
COMMENT ON COLUMN ha_knowledge_sources.updated_at IS 'Knowledge source update timestamp.';

COMMENT ON TABLE ha_knowledge_chunks IS 'RAG searchable chunks derived from governed knowledge sources.';
COMMENT ON COLUMN ha_knowledge_chunks.id IS 'Stable knowledge chunk id.';
COMMENT ON COLUMN ha_knowledge_chunks.source_id IS 'Knowledge source id.';
COMMENT ON COLUMN ha_knowledge_chunks.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_knowledge_chunks.title IS 'Knowledge source title copied for citation.';
COMMENT ON COLUMN ha_knowledge_chunks.version IS 'Knowledge source version copied for citation.';
COMMENT ON COLUMN ha_knowledge_chunks.chunk_index IS 'Chunk order within the source.';
COMMENT ON COLUMN ha_knowledge_chunks.content IS 'Chunk text used only after permission filtering.';
COMMENT ON COLUMN ha_knowledge_chunks.tokens_json IS 'Search tokens serialized as JSON text.';

COMMENT ON TABLE ha_rag_metrics IS 'RAG retrieval metrics for hit rate, permission filtering, and no-answer analysis.';
COMMENT ON COLUMN ha_rag_metrics.id IS 'Database generated metric id.';
COMMENT ON COLUMN ha_rag_metrics.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_rag_metrics.user_id IS 'User associated with retrieval.';
COMMENT ON COLUMN ha_rag_metrics.query_text IS 'Original retrieval query stored for governed analytics.';
COMMENT ON COLUMN ha_rag_metrics.hit IS 'Whether retrieval produced accessible evidence.';
COMMENT ON COLUMN ha_rag_metrics.candidate_count IS 'Candidate chunk count before permission filtering.';
COMMENT ON COLUMN ha_rag_metrics.permitted_count IS 'Candidate chunk count after permission filtering.';
COMMENT ON COLUMN ha_rag_metrics.failure_reason IS 'No-answer or retrieval failure reason code.';
COMMENT ON COLUMN ha_rag_metrics.created_at IS 'Metric creation timestamp.';

COMMENT ON TABLE ha_rag_feedback IS 'User feedback for RAG answers and no-answer outcomes.';
COMMENT ON COLUMN ha_rag_feedback.id IS 'Database generated feedback id.';
COMMENT ON COLUMN ha_rag_feedback.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_rag_feedback.user_id IS 'User associated with feedback.';
COMMENT ON COLUMN ha_rag_feedback.query_text IS 'Original retrieval query associated with feedback.';
COMMENT ON COLUMN ha_rag_feedback.helpful IS 'Whether the user marked the answer helpful.';
COMMENT ON COLUMN ha_rag_feedback.comment_text IS 'Optional feedback comment text.';
COMMENT ON COLUMN ha_rag_feedback.created_at IS 'Feedback creation timestamp.';

COMMENT ON TABLE ha_tool_definitions IS 'Governed tool registry with schema, permission, risk, and audit policy.';
COMMENT ON COLUMN ha_tool_definitions.id IS 'Application generated tool id.';
COMMENT ON COLUMN ha_tool_definitions.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_tool_definitions.name IS 'Tool name exposed to orchestrators.';
COMMENT ON COLUMN ha_tool_definitions.description IS 'Tool purpose description.';
COMMENT ON COLUMN ha_tool_definitions.owner_system IS 'Owning enterprise system.';
COMMENT ON COLUMN ha_tool_definitions.owner_id IS 'Tool owner user or service id.';
COMMENT ON COLUMN ha_tool_definitions.source_type IS 'Tool source type such as internal, MCP, or agent.';
COMMENT ON COLUMN ha_tool_definitions.source_ref IS 'Opaque tool source reference.';
COMMENT ON COLUMN ha_tool_definitions.risk_level IS 'Governance risk level.';
COMMENT ON COLUMN ha_tool_definitions.mutating IS 'Whether tool execution can mutate external state.';
COMMENT ON COLUMN ha_tool_definitions.enabled IS 'Whether the tool can be executed.';
COMMENT ON COLUMN ha_tool_definitions.parameter_schema_json IS 'Parameter schema serialized as JSON text.';
COMMENT ON COLUMN ha_tool_definitions.permission_policy_json IS 'Permission policy serialized as JSON text.';
COMMENT ON COLUMN ha_tool_definitions.audit_policy_json IS 'Audit policy serialized as JSON text.';
COMMENT ON COLUMN ha_tool_definitions.created_at IS 'Tool registration timestamp.';
COMMENT ON COLUMN ha_tool_definitions.updated_at IS 'Tool update timestamp.';

COMMENT ON TABLE ha_tool_audit_records IS 'Tool execution audit records with sanitized input and output.';
COMMENT ON COLUMN ha_tool_audit_records.id IS 'Application generated tool audit id.';
COMMENT ON COLUMN ha_tool_audit_records.occurred_at IS 'Tool audit event timestamp.';
COMMENT ON COLUMN ha_tool_audit_records.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_tool_audit_records.user_id IS 'User isolation key.';
COMMENT ON COLUMN ha_tool_audit_records.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_tool_audit_records.session_id IS 'Session isolation key.';
COMMENT ON COLUMN ha_tool_audit_records.tool_id IS 'Tool definition id.';
COMMENT ON COLUMN ha_tool_audit_records.tool_name IS 'Tool name at execution time.';
COMMENT ON COLUMN ha_tool_audit_records.source_type IS 'Tool source type at execution time.';
COMMENT ON COLUMN ha_tool_audit_records.risk_level IS 'Tool risk level at execution time.';
COMMENT ON COLUMN ha_tool_audit_records.status IS 'Tool execution status.';
COMMENT ON COLUMN ha_tool_audit_records.sanitized_input_json IS 'Sanitized tool input serialized as JSON text.';
COMMENT ON COLUMN ha_tool_audit_records.sanitized_output_json IS 'Sanitized tool output serialized as JSON text.';
COMMENT ON COLUMN ha_tool_audit_records.duration_millis IS 'Tool execution duration in milliseconds.';
COMMENT ON COLUMN ha_tool_audit_records.approval_id IS 'High-risk approval id when present.';
COMMENT ON COLUMN ha_tool_audit_records.reviewer_id IS 'High-risk reviewer id when present.';
COMMENT ON COLUMN ha_tool_audit_records.idempotency_key IS 'Tool idempotency key supplied by caller.';
COMMENT ON COLUMN ha_tool_audit_records.failure_reason IS 'Execution denial or failure reason.';

COMMENT ON TABLE ha_tool_idempotency_records IS 'Stored tool results used to enforce idempotent mutating executions.';
COMMENT ON COLUMN ha_tool_idempotency_records.idempotency_key IS 'Stable idempotency key for tenant, tool, and caller key.';
COMMENT ON COLUMN ha_tool_idempotency_records.parameter_fingerprint IS 'Canonical parameter fingerprint used for conflict detection.';
COMMENT ON COLUMN ha_tool_idempotency_records.result_json IS 'Stored tool execution result serialized as JSON text.';
COMMENT ON COLUMN ha_tool_idempotency_records.created_at IS 'Idempotency record creation timestamp.';

COMMENT ON TABLE ha_telemetry_events IS 'Runtime telemetry events for API, RAG, tool, budget, and orchestration flows.';
COMMENT ON COLUMN ha_telemetry_events.id IS 'Application generated telemetry event id.';
COMMENT ON COLUMN ha_telemetry_events.occurred_at IS 'Telemetry event timestamp.';
COMMENT ON COLUMN ha_telemetry_events.type IS 'Telemetry event type.';
COMMENT ON COLUMN ha_telemetry_events.tenant_id IS 'Tenant isolation key.';
COMMENT ON COLUMN ha_telemetry_events.user_id IS 'User isolation key.';
COMMENT ON COLUMN ha_telemetry_events.agent_id IS 'Agent isolation key.';
COMMENT ON COLUMN ha_telemetry_events.component IS 'Component that emitted the event.';
COMMENT ON COLUMN ha_telemetry_events.duration_millis IS 'Observed duration in milliseconds.';
COMMENT ON COLUMN ha_telemetry_events.attributes_json IS 'Telemetry attributes serialized as JSON text.';
